//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms_Wcf.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteBag", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Exemplo.DTO")]
    [System.SerializableAttribute()]
    public partial class ClienteBag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsForms_Wcf.ServiceReference1.ContatoBag[] ContatosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WindowsForms_Wcf.ServiceReference1.ContatoBag[] Contatos {
            get {
                return this.ContatosField;
            }
            set {
                if ((object.ReferenceEquals(this.ContatosField, value) != true)) {
                    this.ContatosField = value;
                    this.RaisePropertyChanged("Contatos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obs {
            get {
                return this.ObsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsField, value) != true)) {
                    this.ObsField = value;
                    this.RaisePropertyChanged("Obs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContatoBag", Namespace="http://schemas.datacontract.org/2004/07/Wcf_Exemplo.DTO")]
    [System.SerializableAttribute()]
    public partial class ContatoBag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((this.ClienteField.Equals(value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateClient", ReplyAction="http://tempuri.org/IService1/CreateClientResponse")]
        bool CreateClient();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateClient", ReplyAction="http://tempuri.org/IService1/CreateClientResponse")]
        System.Threading.Tasks.Task<bool> CreateClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        bool DeleteClient(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteClient", ReplyAction="http://tempuri.org/IService1/DeleteClientResponse")]
        System.Threading.Tasks.Task<bool> DeleteClientAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchClient", ReplyAction="http://tempuri.org/IService1/SearchClientResponse")]
        WindowsForms_Wcf.ServiceReference1.ClienteBag[] SearchClient(string query, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchClient", ReplyAction="http://tempuri.org/IService1/SearchClientResponse")]
        System.Threading.Tasks.Task<WindowsForms_Wcf.ServiceReference1.ClienteBag[]> SearchClientAsync(string query, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClient", ReplyAction="http://tempuri.org/IService1/UpdateClientResponse")]
        bool UpdateClient(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateClient", ReplyAction="http://tempuri.org/IService1/UpdateClientResponse")]
        System.Threading.Tasks.Task<bool> UpdateClientAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateContact", ReplyAction="http://tempuri.org/IService1/CreateContactResponse")]
        WindowsForms_Wcf.ServiceReference1.ContatoBag CreateContact(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateContact", ReplyAction="http://tempuri.org/IService1/CreateContactResponse")]
        System.Threading.Tasks.Task<WindowsForms_Wcf.ServiceReference1.ContatoBag> CreateContactAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteContact", ReplyAction="http://tempuri.org/IService1/DeleteContactResponse")]
        bool DeleteContact(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj, WindowsForms_Wcf.ServiceReference1.ContatoBag conObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteContact", ReplyAction="http://tempuri.org/IService1/DeleteContactResponse")]
        System.Threading.Tasks.Task<bool> DeleteContactAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj, WindowsForms_Wcf.ServiceReference1.ContatoBag conObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchContact", ReplyAction="http://tempuri.org/IService1/SearchContactResponse")]
        WindowsForms_Wcf.ServiceReference1.ContatoBag[] SearchContact(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchContact", ReplyAction="http://tempuri.org/IService1/SearchContactResponse")]
        System.Threading.Tasks.Task<WindowsForms_Wcf.ServiceReference1.ContatoBag[]> SearchContactAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsForms_Wcf.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsForms_Wcf.ServiceReference1.IService1>, WindowsForms_Wcf.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateClient() {
            return base.Channel.CreateClient();
        }
        
        public System.Threading.Tasks.Task<bool> CreateClientAsync() {
            return base.Channel.CreateClientAsync();
        }
        
        public bool DeleteClient(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.DeleteClient(cliObj);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClientAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.DeleteClientAsync(cliObj);
        }
        
        public WindowsForms_Wcf.ServiceReference1.ClienteBag[] SearchClient(string query, string value) {
            return base.Channel.SearchClient(query, value);
        }
        
        public System.Threading.Tasks.Task<WindowsForms_Wcf.ServiceReference1.ClienteBag[]> SearchClientAsync(string query, string value) {
            return base.Channel.SearchClientAsync(query, value);
        }
        
        public bool UpdateClient(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.UpdateClient(cliObj);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClientAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.UpdateClientAsync(cliObj);
        }
        
        public WindowsForms_Wcf.ServiceReference1.ContatoBag CreateContact(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.CreateContact(cliObj);
        }
        
        public System.Threading.Tasks.Task<WindowsForms_Wcf.ServiceReference1.ContatoBag> CreateContactAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.CreateContactAsync(cliObj);
        }
        
        public bool DeleteContact(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj, WindowsForms_Wcf.ServiceReference1.ContatoBag conObj) {
            return base.Channel.DeleteContact(cliObj, conObj);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteContactAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj, WindowsForms_Wcf.ServiceReference1.ContatoBag conObj) {
            return base.Channel.DeleteContactAsync(cliObj, conObj);
        }
        
        public WindowsForms_Wcf.ServiceReference1.ContatoBag[] SearchContact(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.SearchContact(cliObj);
        }
        
        public System.Threading.Tasks.Task<WindowsForms_Wcf.ServiceReference1.ContatoBag[]> SearchContactAsync(WindowsForms_Wcf.ServiceReference1.ClienteBag cliObj) {
            return base.Channel.SearchContactAsync(cliObj);
        }
    }
}
